# Generated by Django 2.2.4 on 2019-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentcointelegraph',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contentcointelegraph',
            name='tags',
        ),
        migrations.AlterUniqueTogether(
            name='contentdailyhodl',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contentdailyhodl',
            name='tags',
        ),
        migrations.AddField(
            model_name='contentcoindesk',
            name='image_url',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contentcoindesk',
            name='information_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentcoindesk',
            name='news_url',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.DeleteModel(
            name='ContentBitcoinist',
        ),
        migrations.DeleteModel(
            name='ContentCoinTelegraph',
        ),
        migrations.DeleteModel(
            name='ContentDailyHodl',
        ),
    ]
