# Generated by Django 2.2.4 on 2019-09-05 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(max_length=128, unique=True)),
                ('AmountSignups', models.IntegerField(default=0)),
                ('AmountReferrals', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount_needed_referrals', models.IntegerField(default=1)),
                ('rewarded_time_days', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='SignedUpUserReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefToken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.Referral')),
            ],
        ),
    ]
