# Generated by Django 2.2.4 on 2019-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20190905_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='Amount_open_payoff',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='referral',
            name='Amount_paid_off',
            field=models.FloatField(default=0),
        ),
    ]
