# Generated by Django 2.2.6 on 2019-11-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_auto_20190928_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='To_be_paid_off',
            field=models.BooleanField(default=False),
        ),
    ]
