# Generated by Django 2.2.6 on 2019-11-09 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0004_referral_to_be_paid_off'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Holders_Name', models.CharField(max_length=256)),
                ('Bank_Name', models.CharField(max_length=256)),
                ('SWIFT', models.CharField(max_length=256)),
                ('reftoken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.Referral')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
