# Generated by Django 2.2.6 on 2019-11-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0005_openpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='openpayout',
            name='IBAN',
            field=models.CharField(default='', max_length=34),
            preserve_default=False,
        ),
    ]
