"""
Django settings for plutus project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os, sys


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

def find_or_create_secret_key():
    """
    Look for secret_key.py and return the SECRET_KEY entry in it if the file exists.
    Otherwise, generate a new secret key, save it in secret_key.py, and return the key.
    """
    SECRET_KEY_DIR = os.path.dirname(__file__)
    SECRET_KEY_FILEPATH = os.path.join(SECRET_KEY_DIR, 'secret_key.py')
    sys.path.insert(1,SECRET_KEY_DIR)

    if os.path.isfile(SECRET_KEY_FILEPATH):
        from secret_key import SECRET_KEY
        return SECRET_KEY
    else:
        from django.utils.crypto import get_random_string
        chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&amp;*(-_=+)'
        new_key = get_random_string(50, chars)
        with open(SECRET_KEY_FILEPATH, 'w') as f:
            f.write("# Django secret key\n# Do NOT check this into version control.\n\nSECRET_KEY = '%s'\n" % new_key)
        from secret_key import SECRET_KEY
        return SECRET_KEY

# Make this unique, and don't share it with anybody.
SECRET_KEY = find_or_create_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
from .debug import DEBUG
DEBUG = DEBUG

ALLOWED_HOSTS = ['127.0.0.1', 'provisn.com', 'dcpacky.space']

DATA_UPLOAD_MAX_MEMORY_SIZE = 25242880

# Application definition

INSTALLED_APPS = [
    'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'cryptapi',
    'captcha',
    #'corsheaders',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'userdashboard',
    'frontpage',
    'password_reset',
    'logentry_admin',
    'maintenancemode',
    'ckeditor',
    'widget_tweaks',

    'django_gravatar',
    'Calendar',
    'referral',
    'taggit',
    'TelegramHandler',
    'TwitterHandler',
    'ContentScraper'
]

MIDDLEWARE = [
    #'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'maintenancemode.middleware.MaintenanceModeMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'plutus.urls'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'hello@provisn.com'
EMAIL_HOST_PASSWORD = 'Nice&Rich69*'
EMAIL_USE_SSL = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': (
            # ...
        ),
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'django.template.context_processors.request',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ]
        },
    },
]

WSGI_APPLICATION = 'plutus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

### If you're working locally use the first database settings and change them accordingly
###
### On the pythonanywhere production server use the settings below.

# Local Debug Settings
from .database_setup import DATABASES


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

STATICFILES_DIRS = (
    #os.path.join(BASE_DIR, 'static'),
    # ...
)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
}

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
    },
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Amsterdam'

USE_I18N = True

USE_L10N = True

USE_TZ = False



AUTH_USER_MODEL = 'userdashboard.CustomUser'
LOGIN_REDIRECT_URL = '/member'
LOGOUT_REDIRECT_URL = '/'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
### Those are some specific changes, which may cause other issues
###
### If you have a problem running collectstatic or using the static files, uncomment STATIC_ROOT
### and maybe comment STATICFILES_DIRS (Will mostly occur during 'manage.py collectstatic'
STATIC_URL = '/static/'
#STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATIC_ROOT = '/home/dcpacky/PycharmProjects/plutus.live/static'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

#Experimental
CSRF_COOKIE_SECURE = True
CSRF_USE_SESSIONS = True


#DOWNTIME_EXEMPT_PATHS = (
#    'cpanel/'
#)

DOWNTIME_EXEMPT_EXACT_URLS = (
    '/cpanel/',
    '/cpanel/auth/group/',
    '/cpanel/downtime/period/',
    '/cpanel/userdashboard/changelog/',
    '/cpanel/userdashboard/customuser/',
    '/cpanel/userdashboard/supportmessage/',

)


CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        #'toolbar_YourCustomToolbarConfig': [
        #    {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
        #    {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
        #    {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
        #    {'name': 'forms',
        #     'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
        #               'HiddenField']},
        #    '/',
        #    {'name': 'basicstyles',
        #     'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
        #    {'name': 'paragraph',
        #     'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
        #               'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
        #               'Language']},
        #    {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
        #    {'name': 'insert',
        #     'items': ['''Image''' 'base64image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']},
        #    '/',
        #    {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
        #    {'name': 'colors', 'items': ['TextColor', 'BGColor']},
        #    {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
        #    {'name': 'about', 'items': ['About']},
        #    '/',  # put this to force next toolbar on new line
        #    {'name': 'yourcustomtools', 'items': [
        #        # put the name of your editor.ui.addButton here
        #        'Preview',
        #        'Maximize',
        #    ]},
        #],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        #'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
         #'height': '300',
         'width': '100%',
         'filebrowserWindowHeight': 725,
         'filebrowserWindowWidth': 940,
         'toolbarCanCollapse': True,
        'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            #'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            #'autocomplete', Taken off because of bugs and nobody likes bugs in their home
            'sourcedialog',
            #'codemirror', Catched another one
            'divarea',
            #'emoji', This one tried to hide
            #'image2',
            'googlesearch',
            'html5video',
            'html5audio',
            'inserthtmlfile',
            # 'N1ED', Those greedy bastards require a subscription
            # 'OpenStreet',
            'textindent',
            'wordcount',
            'notification',
            'videodetector',
            'codesnippet',
            'base64image'
        ]),
    }
}

CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSER_SHOW_DIRS = True
CKEDITOR_RESTRICT_BY_DATE = True
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_FORCE_JPEG_COMPRESSION = True

GRAPPELLI_ADMIN_TITLE = 'Provisn.com'


# Enable / disable maintenance mode.
# Default: False
MAINTENANCE_MODE = False  # or ``False`` and use ``maintenance`` command

# Sequence of URL path regexes to exclude from the maintenance mode.
# Default: ()
MAINTENANCE_IGNORE_URLS = (
    r'^/cpanel/.*',
)

SITE_ID = 1

RECAPTCHA_PUBLIC_KEY = '6Ld24qsUAAAAAFQx0Vj0q557UEQhDqQjfbv2DJNU'
RECAPTCHA_PRIVATE_KEY = '6Ld24qsUAAAAALgO28lE5jDaggttl3CESzp2hpZb'

#RECAPTCHA_DOMAIN = 'www.recaptcha.net'

DATETIME_FORMAT = "d.m.Y H:i:s"

CHAT_WS_SERVER_HOST = 'dcpacky.space'
CHAT_WS_SERVER_PORT = 5002
CHAT_WS_SERVER_PROTOCOL = 'ws'

TAGGIT_FORCE_LOWERCASE = True

ROUNDTABLE_KIWI_HOST_ADDR = 'dcpacky.space/chat'

TWITTER_CONSUMER_KEY = 'XphtyiMssax8rwg16wQSclSEN'
TWITTER_CONSUMER_SECRET = 'ZXUSfxeauAaOWVjaf3Ux5Rt2y3bvTnueDmFNbc2QEEcXFPEgIe'
TWITTER_ACCESS_TOKEN_KEY = '425349343-i0vfsPN8F4jefWrjEC4iw69QEuffOLQijbZLNn7B'
TWITTER_ACCESS_TOKEN_SECRET = 'bYBT5tz1rst2MEZB0F8lMfcSQmgLr6NSr0LX32Gk7zPB4'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 100000

TELEGRAM_PHONE_NUMBER = '39687526978'
TELEGRAM_API_ID = 915368
TELEGRAM_API_HASH = '90b58e536a20d81da1eeb5e9aae64b5a'
TELEGRAM_NAME = 'Provisn'

TELEGRAM_BOT_TOKEN = '745195021:AAHdBXpmb_iQqnkXf2OgvlsjpoB7Q9G4l2g'

CMC_API = '673c55ab-3434-4c6b-a368-52a264ed880f'

#STRIPE_API_KEY = 'sk_test_Ag6h1CDxv23G60wVCuIBXCRV00EmNaQs80'
STRIPE_SECRET_KEY = 'sk_test_Ag6h1CDxv23G60wVCuIBXCRV00EmNaQs80'
STRIPE_PUBLISHABLE_KEY = 'pk_test_NiSakKktbJWtu4srlgOxRE0o00PESxEdin'
STRIPE_WEBHOOK_SECRET = 'whsec_uSV7LuWffPnWufXlDSiwXjx39shbSjOj'

SIGNUP_ENABLED = False
