# Generated by Django 2.2.6 on 2019-11-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentScraper', '0002_auto_20190928_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_alanmasters',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content_alanmasters',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='content_alanmasters',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='content_cryptontez',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content_cryptontez',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='content_cryptontez',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='content_faibik',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content_faibik',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='content_faibik',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='content_khaledabdulaziz',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content_khaledabdulaziz',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='content_khaledabdulaziz',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='content_alanmasters',
            unique_together={('title', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='content_cryptontez',
            unique_together={('title', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='content_faibik',
            unique_together={('title', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='content_khaledabdulaziz',
            unique_together={('title', 'text')},
        ),
        migrations.RemoveField(
            model_name='content_alanmasters',
            name='db_diagram_embed',
        ),
        migrations.RemoveField(
            model_name='content_alanmasters',
            name='diagram_embed',
        ),
        migrations.RemoveField(
            model_name='content_cryptontez',
            name='db_diagram_embed',
        ),
        migrations.RemoveField(
            model_name='content_cryptontez',
            name='diagram_embed',
        ),
        migrations.RemoveField(
            model_name='content_faibik',
            name='db_diagram_embed',
        ),
        migrations.RemoveField(
            model_name='content_faibik',
            name='diagram_embed',
        ),
        migrations.RemoveField(
            model_name='content_khaledabdulaziz',
            name='db_diagram_embed',
        ),
        migrations.RemoveField(
            model_name='content_khaledabdulaziz',
            name='diagram_embed',
        ),
    ]
