# Generated by Django 2.2.4 on 2019-09-22 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0003_auto_20190922_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainevent',
            name='set_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 18, 48, 24, 4090)),
        ),
    ]
