# Generated by Django 2.2.5 on 2019-10-08 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0005_auto_20190928_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing_Fiat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_usd_cent', models.IntegerField()),
                ('subscription_time_in_days', models.IntegerField(default=30)),
                ('amount_uses', models.IntegerField(default=0)),
                ('show_name', models.CharField(blank=True, max_length=128)),
                ('show_on_page', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 23, 40, 33, 439372)),
        ),
    ]
