# Generated by Django 2.2.5 on 2019-10-09 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0006_auto_20191008_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 1, 37, 18, 406039)),
        ),
    ]
