# Generated by Django 2.2.5 on 2019-10-09 04:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0007_auto_20191009_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 4, 44, 17, 355972)),
        ),
        migrations.CreateModel(
            name='Payment_Fiat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('payment_amount', models.IntegerField()),
                ('payment_fulfilled', models.BooleanField(default=False)),
                ('pricing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userdashboard.Pricing_Fiat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
