# Generated by Django 2.2.5 on 2019-10-10 02:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0009_auto_20191010_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_fiat',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment_fiat',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 10, 2, 41, 52, 341191)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 2, 41, 52, 338993)),
        ),
    ]
