# Generated by Django 2.2.6 on 2019-10-14 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0010_auto_20191010_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_Values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=3)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 19, 59, 15, 493490)),
        ),
        migrations.AlterField(
            model_name='payment_fiat',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 19, 59, 15, 495753)),
        ),
    ]
