# Generated by Django 2.2.6 on 2019-10-14 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0011_auto_20191014_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_values',
            name='value_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 20, 0, 48, 190680)),
        ),
        migrations.AlterField(
            model_name='payment_fiat',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 20, 0, 48, 192863)),
        ),
    ]
