# Generated by Django 2.2.6 on 2019-10-14 20:08

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0012_auto_20191014_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_values',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='currency_values',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 20, 8, 48, 286850)),
        ),
        migrations.AlterField(
            model_name='payment_fiat',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
