# Generated by Django 2.2.6 on 2019-10-14 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0013_auto_20191014_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_values',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 20, 10, 25, 576965)),
        ),
    ]
