# Generated by Django 2.2.6 on 2019-10-14 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0014_auto_20191014_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_values',
            name='value_usd',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 20, 17, 22, 984437)),
        ),
    ]
