# Generated by Django 2.2.6 on 2019-10-15 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0015_auto_20191014_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing_fiat',
            old_name='amount_uses',
            new_name='amount_uses_eth',
        ),
        migrations.AddField(
            model_name='pricing_fiat',
            name='amount_uses_btc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricing_fiat',
            name='amount_uses_usd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 23, 35, 32, 111620)),
        ),
    ]
