# Generated by Django 2.2.6 on 2019-10-16 00:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0016_auto_20191015_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Crypto',
            fields=[
                ('coin', models.CharField(max_length=200)),
                ('value', models.FloatField()),
                ('browser_request', models.TextField()),
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_done', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=3)),
                ('pricing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userdashboard.Pricing_Fiat')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 0, 5, 30, 419845)),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='payment_crypto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
