# Generated by Django 2.2.6 on 2019-10-16 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0019_auto_20191016_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currency_Values',
            new_name='Currency_Value',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 31, 2, 56, 21, 209961)),
        ),
    ]
