# Generated by Django 2.2.6 on 2019-10-17 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0020_auto_20191016_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_crypto',
            name='currency',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 19, 11, 25, 825862)),
        ),
    ]
