# Generated by Django 2.2.6 on 2019-10-20 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0021_auto_20191017_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_fiat',
            name='key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 4, 49, 44, 257023)),
        ),
    ]
