# Generated by Django 2.2.6 on 2019-10-20 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0023_auto_20191020_0451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsedCoupons',
            new_name='UsedCoupon',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 4, 53, 44, 45692)),
        ),
    ]
