# Generated by Django 2.2.6 on 2019-10-21 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0024_auto_20191020_0453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricing_Crypto',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 22, 36, 40, 176577)),
        ),
    ]
