# Generated by Django 2.2.6 on 2019-10-21 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0026_auto_20191021_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_fiat',
            name='recurring_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 22, 52, 13, 780964)),
        ),
    ]
