# Generated by Django 2.2.6 on 2019-10-27 15:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0027_auto_20191021_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 15, 6, 17, 59942)),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256)),
                ('amount_due', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('amount_remaining', models.IntegerField()),
                ('billing_type', models.CharField(max_length=256)),
                ('billing_reason', models.CharField(max_length=256)),
                ('currency', models.CharField(max_length=32)),
                ('account_country', models.CharField(blank=True, max_length=32, null=True)),
                ('invoice_url', models.URLField(blank=True, null=True)),
                ('invoice_pdf', models.URLField(blank=True, null=True)),
                ('payment_intent', models.CharField(max_length=256)),
                ('payment_number', models.CharField(max_length=256)),
                ('subscription_id', models.CharField(blank=True, max_length=256, null=True)),
                ('data', jsonfield.fields.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
