# Generated by Django 2.2.6 on 2019-10-27 19:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0029_auto_20191027_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 19, 52, 6, 718601)),
        ),
    ]
