# Generated by Django 2.2.6 on 2019-10-28 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0030_auto_20191027_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing_fiat',
            name='amount_uses_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 15, 37, 39, 917717)),
        ),
    ]
