# Generated by Django 2.2.6 on 2019-10-29 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0032_auto_20191029_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coinpaprika_id',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 20, 18, 32, 236580)),
        ),
    ]
