# Generated by Django 2.2.6 on 2019-10-29 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0033_auto_20191029_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='slug',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 13, 20, 32, 3, 501693)),
        ),
    ]
