# Generated by Django 2.2.6 on 2019-11-01 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0036_auto_20191101_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenwatchlist',
            old_name='text',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 20, 50, 11, 621647)),
        ),
    ]
