# Generated by Django 2.2.6 on 2019-11-05 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0038_auto_20191103_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 16, 24, 39, 993050)),
        ),
        migrations.AlterField(
            model_name='tokenwatchlist',
            name='coin_icon',
            field=models.ImageField(blank=True, null=True, upload_to='token_spotlight_icons/ca68a411-f841-422c-a3f4-73c5ef1689b4/'),
        ),
        migrations.CreateModel(
            name='ActiveSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='userdashboard.Invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
