# Generated by Django 2.2.6 on 2019-11-06 01:54

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0039_auto_20191105_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenwatchlist',
            name='Markets',
        ),
        migrations.RemoveField(
            model_name='tokenwatchlist',
            name='Specifications',
        ),
        migrations.RemoveField(
            model_name='tokenwatchlist',
            name='Tokenomics',
        ),
        migrations.RemoveField(
            model_name='tokenwatchlist',
            name='description',
        ),
        migrations.AddField(
            model_name='tokenwatchlist',
            name='About',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='tokenwatchlist',
            name='Product',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 21, 1, 53, 58, 958173)),
        ),
        migrations.AlterField(
            model_name='tokenwatchlist',
            name='coin_icon',
            field=models.ImageField(blank=True, null=True, upload_to='token_spotlight_icons/4d93d11d-ae40-4d86-9ac7-72dfaf79e860/'),
        ),
    ]
