# Generated by Django 2.2.6 on 2019-11-09 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0040_auto_20191106_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalanalysi',
            name='diagram_embed',
        ),
        migrations.AddField(
            model_name='pricing_fiat',
            name='saving',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalanalysi',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='technicalanalysi',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 14, 10, 44, 476790)),
        ),
        migrations.AlterField(
            model_name='tokenwatchlist',
            name='coin_icon',
            field=models.ImageField(blank=True, null=True, upload_to='token_spotlight_icons/8c6df46d-1c70-4537-90bb-f9e874718894/'),
        ),
    ]
