# Generated by Django 2.2.6 on 2019-11-09 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0041_auto_20191109_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenwatchlist',
            name='title',
        ),
        migrations.AlterField(
            model_name='blockchainevent',
            name='color_class',
            field=models.TextField(default='event_color_green', max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 16, 7, 59, 940987)),
        ),
        migrations.AlterField(
            model_name='tokenwatchlist',
            name='coin_icon',
            field=models.ImageField(blank=True, null=True, upload_to='token_spotlight_icons/2be1777e-157e-484b-a62a-8ea085adf7bc/'),
        ),
    ]
