# Generated by Django 2.2.6 on 2019-11-09 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdashboard', '0042_auto_20191109_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_until',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 16, 10, 18, 490275)),
        ),
        migrations.AlterField(
            model_name='tokenwatchlist',
            name='coin_icon',
            field=models.ImageField(blank=True, null=True, upload_to='token_spotlight_icons/b01f30be-8d2a-4044-bc55-8826cd2f2645/'),
        ),
    ]
